// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKei6CVgt1BbZfAW-Xjz2zhRt02zmhosE',
    appId: '1:756899764697:web:f63f9da79888953441e1c8',
    messagingSenderId: '756899764697',
    projectId: 'baglanbek-e3407',
    authDomain: 'baglanbek-e3407.firebaseapp.com',
    storageBucket: 'baglanbek-e3407.firebasestorage.app',
    measurementId: 'G-GXW8KF5P8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdwGIEjzkNjP9cO9_DEMbBSdfDm103ZeY',
    appId: '1:756899764697:android:fa77d6e73cc0f5fd41e1c8',
    messagingSenderId: '756899764697',
    projectId: 'baglanbek-e3407',
    storageBucket: 'baglanbek-e3407.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_n4wNCEZ208fp9qMeIxr3WGUaZmnS-Bg',
    appId: '1:756899764697:ios:0b33547f5af0beab41e1c8',
    messagingSenderId: '756899764697',
    projectId: 'baglanbek-e3407',
    storageBucket: 'baglanbek-e3407.firebasestorage.app',
    iosBundleId: 'com.example.loginRegisterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_n4wNCEZ208fp9qMeIxr3WGUaZmnS-Bg',
    appId: '1:756899764697:ios:0b33547f5af0beab41e1c8',
    messagingSenderId: '756899764697',
    projectId: 'baglanbek-e3407',
    storageBucket: 'baglanbek-e3407.firebasestorage.app',
    iosBundleId: 'com.example.loginRegisterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKei6CVgt1BbZfAW-Xjz2zhRt02zmhosE',
    appId: '1:756899764697:web:00fb6fd5a8d7228241e1c8',
    messagingSenderId: '756899764697',
    projectId: 'baglanbek-e3407',
    authDomain: 'baglanbek-e3407.firebaseapp.com',
    storageBucket: 'baglanbek-e3407.firebasestorage.app',
    measurementId: 'G-D1PL4XS9B4',
  );
}
